### ISSUE TITLE
.env not loading without .env.local

### ISSUE THREAD

**Issue by jessedyck** [pantheon-systems/wordpress-composer-managed#31]
Based on the current logic of selecting the appropriate env file, the `.env` is not getting loaded unless I _also_ have a `.env.local`.

Line 36 here does not include `.env`:
https://github.com/pantheon-systems/wordpress-composer-managed/blob/3318e7eb07b996b69ea4da801808092bd6225a05/config/application.php#L34-L36

So when `load()` is called on line 40, `$env_files` contains only `.env.pantheon`, even though the conditional _is_ checking that `.env` exists prior to loading:
https://github.com/pantheon-systems/wordpress-composer-managed/blob/3318e7eb07b996b69ea4da801808092bd6225a05/config/application.php#L38-L40

## Expected

`.env` should load whether or not `.env.local` exists.

## Actual
`.env` is only loaded if `.env.local` exists.

## Solution
This is likely as simple as adding `.env` at index 0 in the array on line 36. That would more closely match how Bedrock handles it:

https://github.com/roots/bedrock/blob/master/config/application.php#L32-L43

I'm happy to submit a PR! just wanted to open a discussion first.

**Comment by scottbuscemi** [comment]
@jessedyck Good catch! A PR would be awesome, but otherwise we'll write up a fix for this next week.

**Comment by kporras07** [comment]
This was now released to the actual upstream.
