### ISSUE TITLE
WP_ENV value in .env is not initiating the correct WordPress environment.

### ISSUE THREAD

**Issue by saqibsarwar** [pantheon-systems/wordpress-composer-managed#37]
I have to exclusively add `WP_ENVIRONMENT_TYPE='development'` to _.env_ file to enable the WordPress development environment.

I think `WP_ENV` value that already exists in _.env_ file should be used to set the WordPress environment.

https://github.com/pantheon-systems/wordpress-composer-managed/blob/4b558e3a249a79e4c4b7033ad61581b7f7285567/.env.example#L9

Thanks

**Comment by kporras07** [comment]
Hi @saqibsarwar 

I just created a ticket to look into this.

Thanks!

**Comment by jspellman814** [comment]
Hi @saqibsarwar thanks for this report. Is this meant for local development? Pantheon does not currently have any plans to support environment-specific configuration files.

**Comment by jspellman814** [comment]
Hi @saqibsarwar thanks for this report. Pantheon does not have any plans to support environment-specific configuration files at this time.

Is this meant for local development?

**Comment by scottbuscemi** [comment]
@saqibsarwar 👋🏼 Hello! I'd love to know how you're using `WP_ENVIRONMENT_TYPE` for your sites?

**Comment by scottbuscemi** [comment]
I'm closing this since we haven't heard back, but we can re-open in the future. TY!
