### ISSUE TITLE
composer install-sage fails when using a 'string' instead of dashes-underscores

### ISSUE THREAD

**Issue by cleverington** [pantheon-systems/wordpress-composer-managed#72]
## Scenario

I ran `composer install-sage` in order to crash-test the Sage theme on Pantheon.

Instead of telling it I wanted a theme along the lines of `feeling-sage` or just `sage`, I told the installer to create for me a theme named `Feeling Sage`. (Forgive the ADHD, I assumed the instructions were on 'what a theme is' and not 'what the folder-name is'! 😆 😆

**This failed by:**
1. Not having a folder named `Feeling`.
2. Trying to parse a version constraint named `Sage`.
3. Deleting the entire contents of `composer.json`, committing the change, and pushing to Pantheon! 😈 
4. Yay! It's all broken. Oh what a world.... haha.

### Fix the "Input" validation

On line 90 of `private/scripts/sage-theme-install.sh`, it runs validation against if the User says "**No**" or "no" or "N" or "n".

It would make more sense to validate **for** 'Yes', 'yes', etc.

### Option 1 - Reject Strings with Spaces
Though less ideal, at least rejecting the 'strings with spaces' means the **rest** of the script won't fail due to a mistyped 'Read' statement.

Would need to add some validation around line 78 of `private/scripts/sage-theme-install.sh` ( `read -p "Theme name: " -r sagename` ) which rejects and re-prompts the user to 'try again'.

Possibly a recursive function that runs until either the user quits or gets it right?

(Please pardon 'bad Bash'. Been a while since I've done up a bash script. lol.)

```bash
  read -p "Theme name: " -r sagename
  confirmThemeName "$sagename"
  

function confirmThemeName( ) {
  if [[ $sagename = *[[:space:]]* ]]
  then
      echo "Invalid theme name. Please avoid spaces."
      read -p "Theme name: " -r sagename
      confirmThemeName "$sagename"
  fi
}
```

### Option 2 - Allow Strings with Spaces (Recommended)
This would obviously be the best/smoothest solution, which would require a bit **more** validation on the parsing side, as you'd want to convert the spaces to dashes `-` or underscores `-`. (I say dashes, considering it is mostly a WordPress Best Practice.)

```bash
  read -p "Theme name: " -r sagename
  setThemeName "$sagename"
  

function setThemeName( ) {
  if [[ $sagename = *[[:space:]]* ]]
  then
      echo "Invalid theme name. Converting 'spaces' into dashes '-'."
      tr ' ' '-' < "$sagename"
  fi
}
```

(Could use this same approach via `tr '[A-Z]' '[a-z]' < "$sagename"` to convert 'uppercase' letters to 'lowercase', but that's probably a slippery slope as some themes might be OOO-declared enough to have the theme _itself_ as a Class.  I mean, **I** haven't seen one, but doesn't mean it isn't out there.)

**Comment by cleverington** [comment]
Adding a clarification in a separate task.

Apparently the explody `composer.json` change is a **separate** issue.

**Comment by jazzsequence** [comment]
I was going to say that not entering a theme name that contained spaces was _explicitly_ mentioned in the [docs](https://github.com/pantheon-systems/wordpress-composer-managed/blob/default/docs/Installing-Sage.md#prompt-for-information)...

> It's important at this step, when choosing a theme name, to use a name that does not include spaces. This name will be used as the directory name and slug for the theme and will be used in bash commands which could error or fail if spaces were entered that it was not expecting.

...but as you've provided a whole lot of code to solve the issue, I won't. 😁  Care to make a PR?

**Comment by wturnerharris** [comment]
Literally just ran into this issue myself. Was going really fast and "forgot" to read. 

Got gummed up with the theme name using spaces and the script allowed me to proceed. Following flow of the rest of the script, it should just exit with error message, but plus one on the scripting to "help" me.

**Comment by jazzsequence** [comment]
Tracking internally as BUGS-6034

**Comment by cleverington** [comment]
> ...but as you've provided a whole lot of code to solve the issue, I won't. 😁 Care to make a PR?

Will try later this week.
