### ISSUE TITLE
Usage of '/wp' directory telling WordPress that ALL of WordPress is installed at web/wp/, including Plugins/Themes

### ISSUE THREAD

**Issue by cleverington** [pantheon-systems/wordpress-composer-managed#93]
## Background

1. The "WordPress Root" directory is set in four locations: `config/application.php`, `wp-cli.yml`, `web/wp-config-pantheon.php`, and `web/wp-cli.yml`.
2. With the sym-link files running to the `web/` directory, setting `/wp` as the WordPress directory is unnecessary within either the `config/application.php` and `web/wp-config-pantheon.php`.
3. The current Bootstrapping process **also** tells some WordPress internals that "All of WordPress is installed at `web/wp/` instead of `web/`... including the themes.

## Issue

When running a custom theme that relies on "base theme path" (specifically: Sage), none of the styles/js/etc. actually **loaded** except for those provided by WordPress itself. This is because WordPress attempted to load the styles via `/wp/wp-includes/css/dist/block-library/style.min.css?ver=6.2`,

## What is affected?

I could honestly see this issue affecting *anything* that uses some sort of Compile step in making themes/plugins/etc. work. GravityForms, ACF, etc. possibly?

The reason it affected the Sage Base theme, for example, is because the `base_path()` function actually generates based on _where the theme is_ in relation to the **codebase**, not where _WordPress_ is.
- The "working" directory should have been `/code/web/app/themes/THEME_NAME/public/STUFF`
- The "working" directory was being rewritten to load as `/code/web/wp/app/themes/THEME_NAME/public/STUFF`.

![image](https://user-images.githubusercontent.com/1015474/231883903-e3c463db-065d-43f0-871c-4401ad969171.png)
_(Text from Screenshot: `<link id="app/0-css" rel="stylesheet" href="https://integration-wp-composer-sage-base.pantheonsite.io/wp/app/themes/sage-base/public/css/app.874a0d.css" media="all">`)_

## Recommendation

The sym-link solved the problem that the various `wp/` additions were trying to solve in a non-breaking manner.  Worth testing, but I think removing all of them _except_ `web/wp-cli.yml` would be the correct next-steps.

(The root-level `wp-cli.yml` would just point to `web` instead of `web/wp`. I could potentially see keeping the `web/wp-cli.yml` around to limit CLI-based triggers and actions potentially failing.)

**Comment by jazzsequence** [comment]
Tracked internally as BUGS-6130

**Comment by cleverington** [comment]
**Clarification:**
- _Both_ of the `wp-cli.yml` files should be left alone. 🗡️ ❤️ 
- The `WP_SITEURL` within `.env.local` defaults to `/wp` as well.

We'll pretend I didn't unknowingly break WP-CLI for a day without realizing it.

**Comment by jazzsequence** [comment]
Closing in favor of our internal tracking ticket in preparation of moving this repo to private (see https://github.com/pantheon-systems/wordpress-composer-managed/issues/77#issuecomment-1758207493). It's on the GA roadmap.

**Comment by jazzsequence** [comment]
Fixed in #132
